apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: url-store
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://daprday-2022.documents.azure.com:443/
  - name: masterKey
    secretKeyRef:
      name: cosmosdb
      key:  daprday2022-masterkey
  - name: database
    value: daprday2022
  - name: collection
    value: url_store