apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: url-resiliency
spec:
  policies:
    retries:
      cosmosdbRetry:
        policy: exponential
        maxInterval: 15s
        maxRetries: 10
  targets:
    components:
      url-store:
        outbound:
          retry: cosmosdbRetry