kind: Service
apiVersion: v1
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  selector:
    app: url-shortener
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer